[tool.poetry]
name = "spark"
version = "0.1.0"
description = ""
authors = ["aman pandey <amanpandeyudyalak@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
